#!/bin/bash

# since I'm working with coreos vagrant box
# and root path is read-only there I need to specify
# different base path there - empty DOCKER_REMOTE_PATH
# and DOCKER_CLIENT_PATH works fine if you have native docker

CONFIG="${DOCKER_REMOTE_PATH}${PWD#${DOCKER_CLIENT_PATH}}/dev/config:/app/config"
BIN="${DOCKER_REMOTE_PATH}${PWD#${DOCKER_CLIENT_PATH}}/dev/bin:/app/bin"


if [ "$1" == "link" ]; then

docker run -i -t \
    --rm \
    -w /root \
    --link mariadb:mysql \
    --env-file dev.env \
    -v $BIN \
    -v $CONFIG \
    michaloo/mariadb:dev

else

docker run -i -t \
    --rm \
    -w /root \
    -p 3306:3306 \
    --env-file dev.env \
    --name mariadb \
    -v $BIN \
    -v $CONFIG \
    michaloo/mariadb:dev

fi